[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gaming_stars = "5X2xYZ1oAebuc8NNMHa3LNgATow8QoFPuFraji93psJp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec jest"
